# Generated by Django 3.0.5 on 2020-04-07 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('param', '0001_initial'),
        ('lbworkflow', '0004_processreportlink_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('start_on', models.DateTimeField(verbose_name='Start on')),
                ('end_on', models.DateTimeField(verbose_name='End on')),
                ('leave_days', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Leave days')),
                ('actual_start_on', models.DateTimeField(verbose_name='Actual start on')),
                ('actual_end_on', models.DateTimeField(verbose_name='Actual end on')),
                ('actual_leave_days', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Actual leave days')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('leave_type', models.ForeignKey(limit_choices_to={'is_active': True, 'param_type__code': 'leave_type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='param.Param', verbose_name='Leave Type')),
                ('pinstance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave', to='lbworkflow.ProcessInstance', verbose_name='Process instance')),
            ],
            options={
                'verbose_name': 'Leave',
                'ordering': ['-created_on'],
                'permissions': (),
            },
        ),
    ]
