# Generated by Django 3.0.5 on 2020-04-07 03:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParamType',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('oid', models.IntegerField(default=999, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['oid'],
            },
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('oid', models.IntegerField(default=999, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True)),
                ('param_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='param.ParamType')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='param.Param')),
            ],
            options={
                'ordering': ['oid'],
            },
        ),
    ]
